services:
  db:
    image: mongo
    ports:
      - "8002:27017"

  web:
    build:
      dockerfile: Dockerfile
      context: ./app
    volumes:
      - .:/code
    entrypoint:
      [
        "uvicorn",
        "app.main:app",
        "--reload",
        "--host",
        "0.0.0.0",
        "--port",
        "80",
      ]
    ports:
      - "8001:80"
    image: portfolio-backend
